# Generated by Django 4.2.16 on 2026-02-24 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('load_cdf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WIND_WI_OR_PRE_v01_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.BigIntegerField(blank=True, null=True)),
                ('time_pb5_year', models.IntegerField(blank=True, null=True)),
                ('time_pb5_day_of_year', models.IntegerField(blank=True, null=True)),
                ('time_pb5_elapsed_ms_of_day', models.IntegerField(blank=True, null=True)),
                ('gci_pos_x', models.FloatField(blank=True, null=True)),
                ('gci_pos_y', models.FloatField(blank=True, null=True)),
                ('gci_pos_z', models.FloatField(blank=True, null=True)),
                ('gci_vel_vx', models.FloatField(blank=True, null=True)),
                ('gci_vel_vy', models.FloatField(blank=True, null=True)),
                ('gci_vel_vz', models.FloatField(blank=True, null=True)),
                ('gse_pos_x', models.FloatField(blank=True, null=True)),
                ('gse_pos_y', models.FloatField(blank=True, null=True)),
                ('gse_pos_z', models.FloatField(blank=True, null=True)),
                ('gse_vel_vx', models.FloatField(blank=True, null=True)),
                ('gse_vel_vy', models.FloatField(blank=True, null=True)),
                ('gse_vel_vz', models.FloatField(blank=True, null=True)),
                ('gsm_pos_x', models.FloatField(blank=True, null=True)),
                ('gsm_pos_y', models.FloatField(blank=True, null=True)),
                ('gsm_pos_z', models.FloatField(blank=True, null=True)),
                ('gsm_vel_vx', models.FloatField(blank=True, null=True)),
                ('gsm_vel_vy', models.FloatField(blank=True, null=True)),
                ('gsm_vel_vz', models.FloatField(blank=True, null=True)),
                ('sun_vector_sun_x', models.FloatField(blank=True, null=True)),
                ('sun_vector_sun_y', models.FloatField(blank=True, null=True)),
                ('sun_vector_sun_z', models.FloatField(blank=True, null=True)),
                ('hec_pos_x', models.FloatField(blank=True, null=True)),
                ('hec_pos_y', models.FloatField(blank=True, null=True)),
                ('hec_pos_z', models.FloatField(blank=True, null=True)),
                ('hec_vel_vx', models.FloatField(blank=True, null=True)),
                ('hec_vel_vy', models.FloatField(blank=True, null=True)),
                ('hec_vel_vz', models.FloatField(blank=True, null=True)),
                ('crn_earth', models.IntegerField(blank=True, null=True)),
                ('long_earth', models.FloatField(blank=True, null=True)),
                ('lat_earth', models.FloatField(blank=True, null=True)),
                ('long_space', models.FloatField(blank=True, null=True)),
                ('lat_space', models.FloatField(blank=True, null=True)),
                ('cdf_file', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='WIND_WI_OR_PRE_v01_data_data', to='load_cdf.cdffilestored')),
            ],
        ),
    ]
