# Generated by Django 4.2.16 on 2026-05-28 08:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('directory', models.TextField()),
                ('mission', models.CharField(max_length=100)),
                ('source_name', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=100)),
                ('instrument', models.CharField(max_length=100)),
                ('dataset_version', models.CharField(max_length=100)),
                ('text_description', models.TextField(blank=True, null=True)),
                ('logical_source', models.CharField(blank=True, max_length=200, null=True)),
                ('logical_description', models.TextField(blank=True, null=True)),
                ('pi_name', models.CharField(blank=True, max_length=200, null=True)),
                ('pi_affiliation', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cdf_file_label', models.CharField(max_length=50, unique=True)),
                ('fillval', models.CharField(blank=True, null=True)),
                ('django_field', models.CharField(max_length=200)),
                ('numpy_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('datatype', models.CharField(blank=True, max_length=200, null=True)),
                ('dims', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dim_sizes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_displayed', models.BooleanField(blank=True, default=False, null=True)),
                ('data_category', models.CharField(blank=True, max_length=200, null=True)),
                ('catdesc', models.CharField(blank=True, max_length=200, null=True)),
                ('var_notes', models.TextField(blank=True, null=True)),
                ('depend_0', models.CharField(blank=True, max_length=200, null=True)),
                ('depend_1', models.CharField(blank=True, max_length=200, null=True)),
                ('display_type', models.CharField(blank=True, max_length=200, null=True)),
                ('scaletyp', models.CharField(blank=True, max_length=200, null=True)),
                ('var_logic_type', models.CharField(blank=True, max_length=200, null=True)),
                ('fillval', models.CharField(blank=True, max_length=50, null=True)),
                ('output_format', models.JSONField(blank=True, null=True)),
                ('lablaxis', models.JSONField(blank=True, null=True)),
                ('labl_ptr', models.CharField(blank=True, max_length=200, null=True)),
                ('units', models.JSONField(blank=True, null=True)),
                ('validmin', models.JSONField(blank=True, null=True)),
                ('validmax', models.JSONField(blank=True, null=True)),
                ('scalemin', models.JSONField(blank=True, null=True)),
                ('scalemax', models.JSONField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='load_cdf.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='VariableAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(blank=True, max_length=100, null=True)),
                ('linked_standard_field', models.CharField(blank=True, max_length=100, null=True)),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='load_cdf.variable')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zip_path', models.TextField()),
                ('match_file_path', models.TextField()),
                ('u_tag', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('matchfile_version', models.CharField(blank=True, max_length=100)),
                ('is_initial', models.BooleanField(default=True)),
                ('dataset_created', models.BooleanField(default=False)),
                ('data_tree_created', models.BooleanField(default=False)),
                ('dataset_attributes_created', models.BooleanField(default=False)),
                ('variables_created', models.BooleanField(default=False)),
                ('matchfile_global_applied', models.BooleanField(default=False)),
                ('matchfile_vars_applied', models.BooleanField(default=False)),
                ('dynamic_model_created', models.BooleanField(default=False)),
                ('nrv_created', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='load_cdf.dataset')),
            ],
            options={
                'unique_together': {('u_tag', 'dataset')},
            },
        ),
        migrations.CreateModel(
            name='NRVData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('value', models.JSONField(blank=True, null=True)),
                ('data_type_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nrv_fields', to='load_cdf.datatype')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nrv_data', to='load_cdf.dataset')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nrv_values', to='load_cdf.variable')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=15, null=True)),
                ('message', models.TextField()),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='load_cdf.upload')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('model_file_path', models.TextField()),
                ('dataset_instance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic', to='load_cdf.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('is_array_field', models.BooleanField(blank=True, default=False)),
                ('array_size', models.PositiveIntegerField(blank=True, null=True)),
                ('data_type_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='load_cdf.datatype')),
                ('dynamic_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='load_cdf.dynamicmodel')),
                ('variable_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic', to='load_cdf.variable')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True, null=True)),
                ('linked_standard_field', models.CharField(blank=True, max_length=100, null=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='load_cdf.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='CDFFileStored',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_path', models.CharField(max_length=300)),
                ('loaded', models.BooleanField(default=False)),
                ('saved_rows', models.IntegerField(default=0)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdf_files', to='load_cdf.upload')),
            ],
        ),
    ]
