# Generated by Django 4.2.16 on 2026-10-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_cdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdffilestored',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
